// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	dto "todo_service/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: task
func (_m *Service) CreateTask(task *dto.CreateTaskRequest) (int, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*dto.CreateTaskRequest) (int, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*dto.CreateTaskRequest) int); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*dto.CreateTaskRequest) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
